const TYPES = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
  DECREASE_ITEM_COUNT: 'DECREASE_ITEM_COUNT',
  INCREASE_ITEM_COUNT: 'INCREASE_ITEM_COUNT',
  SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
  CHANGE_ITEM_TYPE: 'CHANGE_ITEM_TYPE',
  FILTER_ITEM_TYPE_PRODUCTS: 'FILTER_PRODUCTS',
  SET_SELECTED_SORTING: 'SET_SELECTED_SORTING',
  SET_PRICE_LOW_TO_HIGH: 'SET_PRICE_LOW_TO_HIGH',
  SET_PRICE_HIGH_TO_LOW: 'SET_PRICE_HIGH_TO_LOW',
  SET_NEW_TO_OLD: 'SET_NEW_TO_OLD',
  SET_OLD_TO_NEW: 'SET_OLD_TO_NEW',
  GET_BRANDS: 'SET_BRANDS',
  SET_SELECTED_BRANDS: 'SET_SELECTED_BRANDS',
  REMOVE_FROM_BRANDS: 'REMOVE_FROM_BRANDS',
  FILTER_BY_BRANDS: 'FILTER_BY_BRANDS',
};

export default TYPES;
